name: build
on:
  workflow_dispatch:
  push:

jobs:
  build-and-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Golang
        uses: actions/setup-go@v2
      - name: Cache Pip
        id: pip-cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/Python
          key: ${{ matrix.os }}-python${{ matrix.python-version }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}
      - name: Install Package Dependencies
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
          python -c "import pytest; print(pytest.__file__)"
          pip show isort
      - name: Cache libjfs
        id: libjfs-cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/Golang/libjfs
          key: ${{ matrix.os }}-golang-libjfs-${{ hashFiles('Makefile') }}
      - name: Run build-libjfs
        if: steps.libjfs-cache.outputs.cache-hit != 'true'
        run: |
          make build_libjfs
          mkdir -p /opt/hostedtoolcache/Golang/libjfs
          mv juicefs/lib/juicefs /opt/hostedtoolcache/Golang/libjfs/juicefs
          mv juicefs/lib/libjfs.so /opt/hostedtoolcache/Golang/libjfs/libjfs.so
      - name: Link libjfs
        run: |
          ln -s juicefs/lib/juicefs /opt/hostedtoolcache/Golang/libjfs/juicefs
          ln -s juicefs/lib/libjfs.so /opt/hostedtoolcache/Golang/libjfs/libjfs.so
      - name: Run style-check
        run: |
          make style_check
      - name: Run static-check
        run: |
          make static_check
      - name: Run unit-test
        run: |
          make test
