name: build
on:
  workflow_dispatch:
  push:

jobs:
  build-and-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, windows-latest, macos-latest]
        # python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-18.04]
        python-version: [3.6]
        include:
        - os: ubuntu-18.04
          pip-path: /opt/hostedtoolcache/Python
          go-path: /opt/hostedtoolcache/Golang
        # - os: macos-latest
        #   pip-path: /Users/runner/hostedtoolcache/Python/
        #   go-path: /Users/runner/hostedtoolcache/Golang
        # - os: windows-latest
        #   pip-path: C:\hostedtoolcache\windows\Python
        #   go-path: C:\hostedtoolcache\windows\Golang
    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Golang
        uses: actions/setup-go@v2
      - name: Cache Pip
        id: pip-cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.pip-path }}
          key: ${{ matrix.os }}-python${{ matrix.python-version }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}
      - name: Install Package Dependencies
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
      - name: Get JuiceFS Version
        id: jfs-version
        run: echo "::set-output name=JUICEFS_VERSION::$(make -s print_libjfs_version)"
      - name: Cache libjfs
        id: libjfs-cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.go-path }}
          key: ${{ matrix.os }}-golang-libjfs${{ steps.jfs-version.outputs.JUICEFS_VERSION }}
      - name: Run build-libjfs_linux for linux/mac
        if: ${{steps.libjfs-cache.outputs.cache-hit != 'true' && matrix.os != 'windows-latest'}}
        run: |
          make build_libjfs_linux
          mkdir -p ${{ matrix.go-path }}/libjfs
          mv juicefs/lib/juicefs ${{ matrix.go-path }}/juicefs
          mv juicefs/lib/libjfs.so ${{ matrix.go-path }}/libjfs.so
      - name: Run build-libjfs_windows
        if: ${{steps.libjfs-cache.outputs.cache-hit != 'true' && matrix.os == 'windows-latest'}}
        run: |
          make build_libjfs_win
          mkdir -p ${{ matrix.go-path }}\libjfs
          mv juicefs\lib\juicefs.exe ${{ matrix.go-path }}\libjfs\juicefs.exe
          mv juicefs\lib\libjfs.dll ${{ matrix.go-path }}\libjfs\libjfs.dll
      - name: Link libjfs linux
        if: matrix.os != 'windows-latest'
        run: |
          pwd
          ln -s ${{ matrix.go-path }}/libjfs/juicefs juicefs/lib/juicefs
          ln -s ${{ matrix.go-path }}/libjfs/libjfs.so juicefs/lib/libjfs.so
      - name: Link libjfs windows
        if: matrix.os == 'windows-latest'
        run: |
          pwd
          ln -s ${{ matrix.go-path }}\libjfs\juicefs.exe juicefs\lib\juicefs.exe
          ln -s ${{ matrix.go-path }}\libjfs\libjfs.dll juicefs\lib\libjfs.dll
      - name: Run style-check
        if: ${{ matrix.python-version == '3.6' && matrix.os != 'windows-latest' }}
        run: |
          make style_check
      - name: Run static-check
        if: ${{ matrix.python-version == '3.6' && matrix.os != 'windows-latest' }}
        run: |
          make static_check
      - name: Run unit-test
        run: |
          make test
