name: build
on:
  workflow_dispatch:
  push:

jobs:
  build-and-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-18.04, macos-latest, windows-latest]
        # python-version: [3.6, 3.7, 3.8, 3.9]
        os: [windows-latest]
        python-version: [3.6]
        include:
          # - os: ubuntu-18.04
          #   pip-path: /opt/hostedtoolcache/Python
          #   libjfs-path: /opt/hostedtoolcache/Golang
          # - os: macos-latest
          #   pip-path: /Users/runner/hostedtoolcache/Python
          #   libjfs-path: /Users/runner/hostedtoolcache/Golang
          - os: windows-latest
            pip-path: C:\hostedtoolcache\windows\Python
            libjfs-path: C:\hostedtoolcache\windows\Golang

    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Golang
        uses: actions/setup-go@v2
      - name: Cache Pip
        id: pip-cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.pip-path }}
          key: ${{ matrix.os }}-python${{ matrix.python-version }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}
      - name: Install Package Dependencies
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
      - name: Get JuiceFS Version
        id: jfs-version
        run: echo "::set-output name=JUICEFS_VERSION::$(make -s print_libjfs_version)"
      - name: Cache libjfs
        id: libjfs-cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.libjfs-path }}/libjfs
          key: ${{ matrix.os }}-golang-libjfs${{ steps.jfs-version.outputs.JUICEFS_VERSION }}
      - name: Run build-libjfs linux/mac
        if: ${{ steps.libjfs-cache.outputs.cache-hit != 'true' && matrix.os != 'windows-latest' }}
        run: |
          make build_libjfs_so
          mkdir -p ${{ matrix.libjfs-path }}/libjfs
          mv juicefs/lib/juicefs ${{ matrix.libjfs-path }}/libjfs/juicefs
          mv juicefs/lib/libjfs.so ${{ matrix.libjfs-path }}/libjfs/libjfs.so

      - name: Run build-libjfs win
        if: ${{ steps.libjfs-cache.outputs.cache-hit != 'true' && matrix.os == 'windows-latest' }}
        run: |
          make build_libjfs_dll
          mkdir -p ${{ matrix.libjfs-path }}/libjfs
          mv juicefs/lib/juicefs.exe ${{ matrix.libjfs-path }}/libjfs/juicefs.exe
          mv juicefs/lib/libjfs.dll ${{ matrix.libjfs-path }}/libjfs/libjfs.dll

      - name: Link libjfs linux/mac
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          ln -s ${{ matrix.libjfs-path }}/libjfs/juicefs juicefs/lib/juicefs
          ln -s ${{ matrix.libjfs-path }}/libjfs/libjfs.so juicefs/lib/libjfs.so
      - name: Link libjfs win
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          ln -s ${{ matrix.libjfs-path }}/libjfs/juicefs.exe juicefs/lib/juicefs.exe
          ln -s ${{ matrix.libjfs-path }}/libjfs/libjfs.dll juicefs/lib/libjfs.dll

      - name: Run style-check
        if: ${{ matrix.python-version == '3.6' && matrix.os != 'windows-latest' }} 
        run: |
          make style_check
      - name: Run static-check
        if: ${{ matrix.python-version == '3.6' && matrix.os != 'windows-latest' }} 
        run: |
          make static_check
      - name: Run unit-test
        run: |
          make test
