name: Windows build&test
on:
  workflow_dispatch:
  push:

jobs:
  build-juicefs-libjfs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    
    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v2
      - name: Set up Golang
        uses: actions/setup-go@v2
      - name: Get JuiceFS Version
        id: jfs-version
        run: echo "::set-output name=JUICEFS_VERSION::$(make -s print_libjfs_version)"
      - name: Cache juicefs and libjfs binary windows
        uses: actions/cache@v2
        id: jfs-cache-win
        with:
          path: |
            ./juicefs/lib/libjfs.dll
            ./juicefs/lib/juicefs.exe
          key: ${{ matrix.os }}-jfs-binary-win-${{ steps.jfs-version.outputs.JUICEFS_VERSION }}

      - name: Install MinGW GCC
        if: ${{ steps.jfs-cache-win.outputs.cache-hit != 'true' }}
        run: |
          sudo apt-get update
          sudo apt-get install gcc-mingw-w64-x86-64

      - name: Run build-libjfs windows
        if: ${{ steps.jfs-cache-win.outputs.cache-hit != 'true' }}
        run: |
          make build_libjfs_dll

      - name: Upload windows jfs binary
        if: matrix.os == 'ubuntu-18.04'
        uses: actions/upload-artifact@v2
        with:
          name: jfs-binary-win-${{ steps.jfs-version.outputs.JUICEFS_VERSION }}
          path: |
            ./juicefs/lib/libjfs.dll
            ./juicefs/lib/juicefs.exe
          retention-days: 1

  build-and-tests:
    needs: build-juicefs-libjfs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.6]
        include:
          - os: windows-latest
            os-key: win
            pip-path: C:\hostedtoolcache\windows\Python

    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache Pip
        id: pip-cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.pip-path }}
          key: ${{ matrix.os }}-python${{ matrix.python-version }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}
      - name: Install Package Dependencies
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
      - name: Get JuiceFS Version
        id: jfs-version
        run: echo "::set-output name=JUICEFS_VERSION::$(make -s print_libjfs_version)"
      - name: Download jfs binary artifact Linux/Mac/Windows
        # if: ${{ matrix.os != 'windows-latest' }}
        uses: actions/download-artifact@v2
        with:
          name: jfs-binary-${{ matrix.os-key }}-${{ steps.jfs-version.outputs.JUICEFS_VERSION }}
          path: ./juicefs/lib/
      - name: Chmod to make juicefs executable windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          chmod 755 ./juicefs/lib/juicefs.exe
          ls -l ./juicefs/lib/juicefs.exe

      - name: Run style-check
        if: ${{ matrix.python-version == '3.6' && matrix.os != 'windows-latest' }} 
        run: |
          make style_check
      - name: Run static-check
        if: ${{ matrix.python-version == '3.6' && matrix.os != 'windows-latest' }} 
        run: |
          make static_check
      - name: Run unit-test
        run: |
          make test
